name: flutter_application_1
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.11.0

dependencies:
  flutter:
    sdk: flutter
  web_socket_channel: ^3.0.0
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  # 1. ADD THIS PACKAGE
  flutter_launcher_icons: ^0.13.1 

flutter:
  uses-material-design: true

# 2. ADD THIS CONFIGURATION SECTION AT THE END
flutter_launcher_icons:
  android: "ic_launcher"
  ios: true
  image_path: "lib/image.png"
  min_sdk_android: 21 # optional